name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

matrix:
  os: ['windows-2019', 'ubuntu-20.04']
  include:
    - os: 'windows-2019'
      triplet: 'x86-windows'
      mono: ''
      bootstrap-vcpkg-cmd: './vcpkg/bootstrap-vcpkg.bat'
    - os: 'ubuntu-20.04'
      triplet: 'x64-linux'
      # To run `nuget.exe` on non-Windows platforms, we must use `mono`.
      mono: 'mono'
      bootstrap-vcpkg-cmd: './vcpkg/bootstrap-vcpkg.sh'

jobs:
  build:
    steps:
      - run: ${{ matrix.bootstrap-vcpkg-cmd }}

      - name: 'Setup NuGet Credentials'
        shell: 'bash'
        # Replace <OWNER> with your organization name
        run: >
          ${{ matrix.mono }} `./vcpkg/vcpkg fetch nuget | tail -n 1`
          sources add
          -source "https://nuget.pkg.github.com/skyrim-multiplayer/index.json"
          -storepasswordincleartext
          -name "GitHub"
          -username "skyrim-multiplayer"
          -password "${{ secrets.GITHUB_TOKEN }}"

      # Omit this step if you're using manifests
      - name: 'vcpkg package restore'
        shell: 'bash'
        run: >
         ./vcpkg/vcpkg install nlohmann-json --triplet ${{ matrix.triplet }}