name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
  VCPKG_FEATURE_FLAGS: 'manifests' #todo - remove once cmake build system added
  #CC: /usr/bin/clang-11
  #CPP: /usr/bin/clang-cpp-11
  #CXX: /usr/bin/clang++-11
  #LD: /usr/bin/ld.lld-11

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - run: clang --version

    - run: ./vcpkg/bootstrap-vcpkg.bat

    - name: 'Setup NuGet Credentials'
      shell: 'bash'
      # Replace <OWNER> with your organization name
      run: >
        `./vcpkg/vcpkg fetch nuget | tail -n 1`
        sources add
        -source "https://nuget.pkg.github.com/skyrim-multiplayer/index.json"
        -storepasswordincleartext
        -name "GitHub"
        -username "skyrim-multiplayer"
        -password "${{ secrets.GITHUB_TOKEN }}"

    # Omit this step if you're using manifests
    - name: 'vcpkg package restore'
      shell: 'bash'
      run: >
       ./vcpkg/vcpkg install --debug --overlay-ports=overlay_ports