name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - run: ./vcpkg/bootstrap-vcpkg.sh

    - name: 'Setup NuGet Credentials'
      shell: 'bash'
      # Replace <OWNER> with your organization name
      run: >
        mono `./vcpkg/vcpkg fetch nuget | tail -n 1`
        sources add
        -source "https://nuget.pkg.github.com/skyrim-multiplayer/index.json"
        -storepasswordincleartext
        -name "GitHub"
        -username "skyrim-multiplayer"
        -password "${{ secrets.GITHUB_TOKEN }}"

    # Omit this step if you're using manifests
    - name: 'vcpkg package restore'
      shell: 'bash'
      run: >
       ./vcpkg/vcpkg install