name: PR Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
  VCPKG_FEATURE_FLAGS: 'manifests'

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: 'true'

    - name: test
      run: mkdir yolo && echo 123 > yolo/kek.txt

    - uses: actions/upload-artifact@v2
      with:
        name: yolo_${{github.sha}}
        path: ${{github.workspace}}/yolo
